import Header from '@/app/modules/administrator/ui/components/header'
import Sidebar from '@/app/modules/administrator/ui/components/sidebar'
import type { Metadata } from 'next'
import { Geist, Geist_Mono, Poppins, Montserrat } from 'next/font/google'

// Configuración de fuentes
const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] })
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] })
const poppins = Poppins({ variable: '--font-poppins', subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] })
const montserrat = Montserrat({ variable: '--font-montserrat', subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function AdminLayout({ children }: { children: React.ReactNode }) {
    return (
      <html lang="es">
        <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${montserrat.variable} antialiased`}>
          {/* Sidebar fijo en la izquierda */}
          <Sidebar />
  
          {/* Header con padding para respetar el sidebar */}
          <Header/>
  
          {/* Main también con padding para respetar el sidebar */}
          <main className="bg-gray-200  min-h-screen flex-grow p-9 pt-4 md:pl-56">{children}</main>
        </body>
      </html>
    )
}
